### ISSUE TITLE
[API] 무한 스크롤 조회

### ISSUE THREAD

**Issue by seaworld0125** [Hoppy-project/mono-repo#10]
## 이슈 내용

무한 스크롤 조회 기능에 대한 논의가 필요합니다.

1. 모임과 게시물 목록 또는 모임에 속한 멤버 목록을 조회할 때 (인스타나 페이스북 처럼) 무한 스크롤로 페이지를 구성하는데, 몇 개씩 데이터가(모임 or 게시글 or 멤버) 조회되는 것이 좋을지 디자인과 프론트 측에서 논의 후 알려주시면 감사하겠습니다.

2. 무한 스크롤용 모임 조회 API는 다음과 같은 형태를 고려하고 있습니다. 

{ 
- "status" : 200, 
- "message" : "HEALTH 카테고리 모임 조회 완료", 
- "responseData" : [
- - {"id" : 19, "url" : "https://aws.s3.....", "title" : "수원 뜨개질 모임", "content" : "주 1회 오프라인 모임", "participants" : 2, "liked" : true}, 
- - {"id" : 15, "url" : "https://aws.s3.....", "title" : "수원역 조기축구회", "content" : "나이제한 없음!", "participants" : 5, "liked" : false}, 
- ... ] 
- "next" : "https://hoppy.kro.kr..."
}

responseData에는 조회된 데이터들의 정보가 List 형태로 담겨서 전달되어질 예정이며, next에는 다음 조회를 진행할 수 있는 url이 전송될 예정입니다. 혹시 보완할 부분이 있다면 피드백 부탁드립니다.

**Comment by yoona-J** [comment]
안녕하세요 태경님.

현재 디자인 상으로 한 줄에 카드가 두 개가 띄워지고 있기 때문에 한 번 스크롤 시 10-14개로 구성되면 좋을 거 같습니다. (짝수)

또한 현재 만들어지고 있는 모든 api 들의 중복되는 body 값 이름이 통일되면 더욱 좋을 듯 합니다.
예시로, 멤버 고유 번호는 memberId / 이미지 파일은 image / 게시물 고유 id는 id 이런 식으로요!

+) 무한 스크롤 api에서는 writer 정보가 같이 들어가면 좋을 듯 합니다 ~! (멤버 고유 id요!)

**Comment by seaworld0125** [comment]
> 안녕하세요 태경님.
> 
> 현재 디자인 상으로 한 줄에 카드가 두 개가 띄워지고 있기 때문에 한 번 스크롤 시 10-14개로 구성되면 좋을 거 같습니다. (짝수)
> 
> 또한 현재 만들어지고 있는 모든 api 들의 중복되는 body 값 이름이 통일되면 더욱 좋을 듯 합니다. 예시로, 멤버 고유 번호는 memberId / 이미지 파일은 image / 게시물 고유 id는 id 이런 식으로요!
> 
> +) 무한 스크롤 api에서는 writer 정보가 같이 들어가면 좋을 듯 합니다 ~! (멤버 고유 id요!)

답변 감사합니다~!

그럼 조회되는 아이템은 14개로 통일하도록 하겠습니다.

그리고 현재 만들어지는 api들의 응답에서 쓰이는 key값은 최대한 통일시켜서 작성하도록 하겠습니다.

+) 혹시 writer 정보라함은 모임의 경우, 모임을 최초로 생성한 사용자를 말씀하시는게 맞을까요?

**Comment by yoona-J** [comment]
> > 안녕하세요 태경님.
> > 현재 디자인 상으로 한 줄에 카드가 두 개가 띄워지고 있기 때문에 한 번 스크롤 시 10-14개로 구성되면 좋을 거 같습니다. (짝수)
> > 또한 현재 만들어지고 있는 모든 api 들의 중복되는 body 값 이름이 통일되면 더욱 좋을 듯 합니다. 예시로, 멤버 고유 번호는 memberId / 이미지 파일은 image / 게시물 고유 id는 id 이런 식으로요!
> > +) 무한 스크롤 api에서는 writer 정보가 같이 들어가면 좋을 듯 합니다 ~! (멤버 고유 id요!)
> 
> 답변 감사합니다~!
> 
> 그럼 조회되는 아이템의 개수는 14개로 통일하겠습니다.
> 
> 그리고 현재 만들어지는 api들의 응답에서 쓰이는 key값은 최대한 통일시켜서 작성하도록 하겠습니다.
> 
> +) 혹시 writer 정보라함은 모임의 경우, 모임을 최초로 생성한 사용자를 말씀하시는게 맞을까요?

네 맞습니다! 게시물을 작성한 작성자 정보가 들어가면 좋을 거 같습니다 :)
