### ISSUE TITLE
[FE & BE] 모임 상세 페이지 조회

### ISSUE THREAD

**Issue by seaworld0125** [Hoppy-project/mono-repo#13]
## 이슈 내용

@yoona-j, @suhyeon0111 

**안녕하세요. 모임 상세 페이지 조회 기능에 대한 논의가 필요합니다.**

1. 한 모임당 멤버를 최대 20명까지 가입할 수 있도록 제한을 걸어둔 상태입니다. 최대 20명 밖에 되지 않기 때문에 프론트 측에서 모임 상세 페이지를 로드할 때 한 번에 모든 멤버(최대 20명)를 response body에 넣어드리려고 하는데 괜찮으신가요?

![image](https://user-images.githubusercontent.com/75168305/178660683-7c07fa03-c361-46ee-a5e9-c9b3ff4d0fe9.png)

2. UX/UI에 모임 상세 페이지를 살펴보면 멤버 목록에 모임장을 표시하고 있는 것을 볼 수 있습니다. 이를 response body에서 표현하는 방법은 두 가지 정도가 있는데요, 어떤 방식이 편하신지 말씀해주시면 이를 토대로 response body를 구성하도록 하겠습니다. 
> 1. 따로 owner 필드를 사용해서 owner 정보를 전달하고 다른 일반 멤버는 모두 participants 배열에 넣는다.
> 2. owner와 일반 멤버 모두 participants에 넣고 owner : false, true로 표현한다.

3. api의 응답 형태는 "일단" 다음과 같은 형태를 고려하고 있습니다. 논의 후 변경될 수 있습니다.

{
- "status" : 200,
- "message" : "모임 상세 페이지 조회 완료",
- "data" : {
- "title" : "수원 뜨개질 모임",
- "url" : "https://aws.s3....photo.png",
- "content" : "주 1회 오프라인으로 모임을 가지는 세이브 더 칠드런 봉사 모임! ...",
- "liked" : false,
- "participants" : [
- {"id" : 19, "name" : "잠자는 쿼카", "owner" : true, "profile" : "https://aws.s3...."},
- {"id" : 15, "name" : "뜨개질 고인물 쿼카", "owner" : false, "profile" : "https://aws.s3...."},
- ]
}

## 요구사항

이슈 내용에서 궁금하신 점이나 논의할 내용 comment로 부탁드립니다. 감사합니다.

## 참고사항

1. 구현 예상 소요 기간 : 논의 완료 후 2일

**Comment by suhyeon0111** [comment]
안녕하세요. 태경님 
올려주신 이슈 확인하고 답글답니다🙂

1. 한번에 로드되도록 response body로 20명 한번에 전달해주시면 될 것 같습니다.
2. 제 생각에는 2번으로 해주시면 편할 것 같습니다.
3. "nextParticipantsUrl"은 프론트 측 로딩 전략에 따라 달라진다는게 무슨 뜻인가요??

**Comment by yoona-J** [comment]
안녕하세요
추가적으로 궁금한 점이 더 있는데요...
participants에서의 id 값은 유저 고유 id 값일까요?

그리고 UI/UX 상에서 보면 가입자의 프로필 사진이 같이 들어가기 때문에 이 부분도 추가하면 좋을 거 같습니다.

**Comment by seaworld0125** [comment]
> 안녕하세요. 태경님 올려주신 이슈 확인하고 답글답니다🙂
> 
> 1. 한번에 로드되도록 response body로 20명 한번에 전달해주시면 될 것 같습니다.
> 2. 제 생각에는 2번으로 해주시면 편할 것 같습니다.
> 3. "nextParticipantsUrl"은 프론트 측 로딩 전략에 따라 달라진다는게 무슨 뜻인가요??

답변 감사합니다😊
3번은 무시하셔도 될 것 같습니다!

**Comment by seaworld0125** [comment]
> 안녕하세요 추가적으로 궁금한 점이 더 있는데요... participants에서의 id 값은 유저 고유 id 값일까요?
> 
> 그리고 UI/UX 상에서 보면 가입자의 프로필 사진이 같이 들어가기 때문에 이 부분도 추가하면 좋을 거 같습니다.

답변 감사합니다🤗
participants에서 id 값은 유저 고유 id 값이 맞습니다. 유저의 프로필 url도 추가하도록 하겠습니다.

**Comment by seaworld0125** [comment]
@yoona-J @suhyeon0111 

안녕하세요!

혹시 카테고리 모임 리스트 조회 화면에서 liked 상태를 확인하고, 

모임 상세페이지로 진입할 때 liked 여부를 가져다가 다시 쓰실 수 있나요? 

그렇게 할 수 있다면 저희 쪽에서 굳이 liked를 재확인할 필요가 없을 것 같아서요. 

답변 부탁드립니다. 감사합니다.

**Comment by yoona-J** [comment]
> @yoona-J @suhyeon0111
> 
> 안녕하세요!
> 
> 혹시 카테고리 모임 리스트 조회 화면에서 liked 상태를 확인하고,
> 
> 모임 상세페이지로 진입할 때 liked 여부를 가져다가 다시 쓰실 수 있는지 궁금합니다.
> 
> 그렇게 할 수 있다면 저희 쪽에서 굳이 liked를 재확인할 필요가 없을 것 같아서요.
> 
> 답변 부탁드립니다. 감사합니다.

안녕하세요 태경님.
차라리 드는 생각은 모임 정보 DB를 하나로 묶어두는 것도 괜찮다고 판단합니다.
모임 리스트 api, 모임 상세페이지 api를 따로 구분하지 않고 모임 정보 api로 하나로 합쳐서 진행하게 되면 api 하나에서 해당되는 값을 props로 가져올 수 있어서요!

그게 아니라 api를 모두 다르게 만드신다면,,, 상세페이지에서 api를 조회할 때 두 api를 모두 불러와 데이터를 중복키를 이용해 합치게 되면 가능은 할 거 같습니다만,,,
그렇게 만드는 거 보다는 api를 통합하는게 더 낫지 않을까 싶네요!

감사합니다 :)

**Comment by seaworld0125** [comment]
@yoona-J @suhyeon0111  

API 업데이트 완료 했습니다. 확인하시고 궁금하신 내용 있으시면 comment 남겨주세요!

https://hoppy.kro.kr/api/docs/api-docs.html#_%EB%AA%A8%EC%9E%84_%EC%83%81%EC%84%B8%EC%A1%B0%ED%9A%8C
