### ISSUE TITLE
[백엔드 & 프론트엔드] API 문서 공유 방식

### ISSUE THREAD

**Issue by seaworld0125** [Hoppy-project/mono-repo#3]
## 이슈 내용

안녕하세요! 다들 주말 잘 보내셨나요 ㅎㅎ

저희 API 문서 공유 방식을 안내해 드리려고 이슈를 생성하게 됐습니다.

우선 API 문서 작성 툴은 처음에 swagger를 이용하고자 했지만 Asciidoc을 이용했습니다.

API 문서는 저희 프로젝트 도메인 [hoppy.kro.kr](https://hoppy.kro.kr)을 통해서 보실 수 있고
[hoppy.kro.kr/api/docs/api-docs.html](https://hoppy.kro.kr/api/docs/api-docs.html) 로 접속하시면 저희 백엔드 측에서 서버로 배포한 api 내역과 사용법을 보실 수 있습니다.
(현재는 health check api만 존재합니다.)

따라서 프론트 측에서 백엔드가 개발한 api를 활용하여 개발하고자 하실 때는 api-docs.html에 보이시는 api를 활용하시면 됩니다.
(모든 백엔드 api는 url에 prefix로 /api 가 붙습니다. 즉, /health 는 /api/health 로 호출하시면 됩니다.)

추가적으로 현재 CI/CD를 통한 무중단 배포가 구성 완료되었고 백엔드 측만 적용되고 있습니다. 프론트측의 자동 배포는 화요일 회의에서 빌드와 실행 관련해서 궁금한 것을 여쭤보고 구성할 예정입니다. 

추가적으로 궁금하신 내용 있으시면 말씀해 주세요.

## 참고사항

Hoppy 서비스 도메인 [hoppy.kro.kr](https://hoppy.kro.kr)

api문서 [hoppy.kro.kr/api/docs/api-docs.html](https://hoppy.kro.kr/api/docs/api-docs.html)

**Comment by Choidaehankr** [comment]
확인했습니다!
